- src/ResourceManager/AzureBackup/Commands.AzureBackup/Models/AzureBackupContainer.cs
> Adding AzureBackupContainer model (initial draft).

- src/ResourceManager/AzureBackup/Commands.AzureBackup/Models/AzureBackupBaseObjects.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup/Models/AzureBackupContainer.cs
1. Renamed ContainerId back to InstanceId.
2. Created ContainerContext base class.
> Made some changes according to previous PR.

- src/ResourceManager/AzureBackup/Commands.AzureBackup/AzureBackupContainerCmdletBase.cs
> Fixes for build break

- src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Vault/SetAzureBackupVaultStorageType.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup/Commands.AzureBackup.csproj
Fixing bugs in set storage type API
> Set storage type API

- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/Commands.AzureBackup.Test.csproj
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupPolicyTests.ps1
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/SessionRecords/Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupPolicyTests/ListProtectionPolicyByNameTests.json
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/SessionRecords/Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupPolicyTests/ListProtectionPolicyTests.json
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/SessionRecords/Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupPolicyTests/NewProtectionPolicyTests.json
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/SessionRecords/Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupPolicyTests/RemoveProtectionPolicyTests.json
- src/ResourceManager/AzureBackup/Commands.AzureBackup/Library/AzureBackupContainerCmdletHelper.cs
Adding container cmdlet helper and pragrawa's test fixes
> Adding container cmdlet helper & pragrawa's test fixes

- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupContainerTests.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupContainerTests.ps1
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupScenarioTests.ps1
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/SessionRecords/Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupContainerTests/AzureBackupMarsContainerScenarioTests.json
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/SessionRecords/Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupScenarioTests/AzureBackupEndToEndTests.json
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/SessionRecords/Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupVaultTests/AzureBackupVaultScenarioTests.json
Merging remaining PSH test cases json files.
> Dev1 pikumar git2

- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupContainerTests.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupItemTestCases.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupItemTestCases.ps1
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupJobTests.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupJobTests.ps1
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupPolicyTests.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/AzureBackupScenarioTests.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/BackupItemTests.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/BackupItemTests.ps1
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/RecoveryPointTests.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/RecoveryPointTests.ps1
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/RestoreItemTests.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup.Test/ScenarioTests/RestoreItemTests.ps1
1. License header
2. Setting CheckIn Trait to acceptance in all tests
3. Removed and sorted unused usings.
> Final Touches

- src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Jobs/AzureBackupJobHelper.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Jobs/GetAzureRMBackupJob.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Jobs/GetAzureRMBackupJobDetails.cs
- src/ResourceManager/AzureBackup/Commands.AzureBackup/Models/JobObjects.cs
Reverts MabOneSdk/azure-powershell#124
> Revert "FI from dev1 into release"

- src/ResourceManager/RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesContainer.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Cmdlets.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CmdletParamEnums.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/Commands.RecoveryServices.Backup.Models.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonEnums.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/IaasVmModels/AzureRmRecoveryServicesIaasVmContainer.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/IaasVmModels/AzureRmRecoveryServicesIaasVmItem.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/IaasVmModels/AzureRmRecoveryServicesIaasVmPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/Commands.RecoveryServices.Backup.Providers.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/PsBackupProviderDC.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/PsBackupProviderManager.cs
> Provider Model and Base Models

- src/ResourceManager/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/SetAzureRmRecoveryServicesPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Cmdlets.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/BaseObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Enums.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/PolicyRetentionObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/PolicyScheduleObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Utils.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/IaasVmModels/AzureRmRecoveryServicesIaasVmPolicy.cs
added placeholders for policy cmdlets and minor updates to policy objects
> added placeholders for policy cmdlets and minor updates to policy objects

- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Enums.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/Commands.RecoveryServices.Backup.Providers.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/Providers/AzureSqlPsBackupProvider.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/PsBackupProviderManager.cs
Adding AzureSql provider skeleton.
> AzureSql provider skeleton.

- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Properties/AssemblyInfo.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.HydraAdapter/Properties/AssemblyInfo.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/Properties/AssemblyInfo.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/Properties/AssemblyInfo.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/ScenarioTests/TestsBase.cs
- src/ResourceManager/RecoveryServices.Backup/Properties/AssemblyInfo.cs
- src/ResourceManager/RecoveryServices.Backup/RecoveryServices.Backup.sln
Added test infra for RS Backup
> Tests Base RS Backup

- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Commands.RecoveryServices.Backup.Helpers.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Conversions/JobConversions.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.HydraAdapter/BMSAPIs/JobAPIs.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/AzureVmModels/AzureRmRecoveryServicesAzureVmJob.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/BaseObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/Commands.RecoveryServices.Backup.Models.csproj
Adding base DC and VM DC of jobs. Added minimilastic translator for the same.
> Jobs base and IaaSVM DCs and basic translation

- src/ResourceManager/RecoveryServices.Backup/CmdletParameterHelpMessages.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/SetAzureRmRecoveryServicesPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Commands.RecoveryServices.Backup.Helpers.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Conversions/RetentionPolicyConversions.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/BaseObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CmdletParamEnums.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Enums.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/PsBackupProviderManager.cs
This contains base skeletons for policy cmdlets and coversion helpers. Tracing and exception handling will be done in next checkin.
> Base skeletons for policy cmdlets and coversion helpers

- src/ResourceManager/RecoveryServices.Backup/CmdletParameterHelpMessages.cs
- src/ResourceManager/RecoveryServices.Backup/CmdletWarningAndErrorMessages.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesJob.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesJobDetails.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/Jobs/WaitAzureRmRecoveryServicesJob.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Cmdlets.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Commands.RecoveryServices.Backup.Helpers.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Conversions/JobConversions.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/HydraHelpers.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.HydraAdapter/BMSAPIs/JobAPIs.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.HydraAdapter/Commands.RecoveryServices.Backup.HydraAdapter.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.HydraAdapter/CommonHelpers.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/BaseObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Enums.cs
- src/ResourceManager/RecoveryServices.Backup/Constants.cs
- src/ResourceManager/RecoveryServices.Backup/RecoveryServicesBackupCmdletBase.cs
Implementation for GetJobs, GetJobDetails and WaitJob cmdlets. Testing is pending.
> Get and Wait implementation for Jobs

- src/ResourceManager/RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesContainer.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Cmdlets.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Utils.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/Commands.RecoveryServices.Backup.Providers.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/IPsBackupProvider.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/Providers/AzureSqlPsBackupProvider.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ContainerTests.ps1
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestGetContainerScenario.json
- src/ResourceManager/RecoveryServices.Backup/Properties/Resources.Designer.cs
- src/ResourceManager/RecoveryServices.Backup/Properties/Resources.resx
- src/ResourceManager/RecoveryServices.Backup/RecoveryServicesBackupVaultCmdletBase.cs
1. Fixed GetContainer bugs
2. Made GetContainer cmdlet provider specific
3. Added the corresponding session records; ensured that the test case is passing in playback mode
> Get Container Fixes

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices/Commands.RecoveryServices.csproj
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices/Common/PSRecoveryServicesClient.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices/Common/PSRecoveryServicesVaultClient.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices/Properties/Resources.Designer.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices/Properties/Resources.resx
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices/Utilities/Utilities.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices/Vault/SetAzureRmRecoveryServicesVaultContext.cs
Moving Set-AzureRMRecoveryServicesVaultContext cmdlet to common project RecoveryServices
Will do cleanup for this in AzureRM.RecoveryServices.Backup before checkin of this.
> Set-RS VaultContext changes

- src/ResourceManager/RecoveryServices.Backup/Cmdlets/Item/DisableAzureRmRecoveryServicesProtection.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/Item/EnableAzureRmRecoveryServicesProtection.cs
- src/ResourceManager/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/RemoveAzureRmRecoveryServicesPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
> Addinng positions to ps params

- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
- src/ResourceManager/RecoveryServices.Backup/RecoveryServices.Backup.sln
Fixed issues with Backup and checked in working session record
> Added Backup Test Record

- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Enums.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Providers/PsBackupProviderManager.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesBackupManagementServer.cs
Removing SCDPM from Backup Management Type as Get Container should not show SCDPM
> Removing SCDPM from BackupManagementType list in Get Container.

- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Conversions/JobConversions.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Conversions/SchedulePolicyConversions.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/HelperUtils.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/ServiceClientHelpers.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Helpers/Validations/PolicyValidations.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Logger/Logger.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/AzureVmModels/AzureVmContainer.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/AzureVmModels/AzureVmItem.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/AzureVmModels/AzureVmJob.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/AzureVmModels/AzureVmPolicy.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/BaseObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Enums.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/PolicyRetentionObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/PolicyScheduleObjects.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/CommonModels/Utils.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/DpmModels/DpmBackupEngine.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Models/MabModels/MabContainer.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup/Cmdlets/Backup/BackupAzureRmRecoveryServicesBackupItem.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesBackupContainer.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup/Cmdlets/Jobs/StopAzureRmRecoveryServicesBackupJob.cs
- src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup/Cmdlets/RecoveryPoint/GetAzureRmRecoveryServicesBackupRecoveryPoint.cs
> Fixing 7349803 in Helper, Logger and Models Layers

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/AzureFileShareModels/AzureFileShareItem.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/AzureFileShareModels/AzureFileSharePolicy.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/AzureModels/AzurePolicy.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Commands.RecoveryServices.Backup.Models.csproj
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
changed base class for AzureFileSharePolicy
rebase changes
renaming azurefileshareextended info
rebase changes
---
> [do not merge] Testing Ignite scenario 

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Properties/Resources.resx
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ContainerTests.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ContainerTests.ps1
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/Cmdlets/Container/UnregisterAzureRmRecoveryServicesBackupContainer.cs
> [REBASE]Added Azure File Share support to disable container

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Helpers/Conversions/JobConversions.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/AzureFileShareModels/AzureFileShareJob.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/AzureModels/AzureJob.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Commands.RecoveryServices.Backup.Models.csproj
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.ps1
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/IaasVm/JobTests.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesBackupJob.cs
> [REBASE] Get job cmdlet

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Helpers/Conversions/RecoveryPointConversions.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/AzureFileShareModels/AzureFileShareRecoveryPoint.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/AzureModels/AzureRecoveryPoint.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Commands.RecoveryServices.Backup.Models.csproj
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
> [REBASE] Added Azure File Share support to get RPs

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.ps1
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesBackupJobDetails.cs
> added AFS support to get job details

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.ps1
> Added AFS support to wait job

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.ps1
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/Cmdlets/Jobs/StopAzureRmRecoveryServicesBackupJob.cs
> Added AFS support to stop job

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/CommonModels/Utils.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/PolicyTests.ps1
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesBackupProtectionPolicy.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Enable-AzureRmRecoveryServicesBackupProtection.md
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Get-AzureRmRecoveryServicesBackupContainer.md
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Get-AzureRmRecoveryServicesBackupItem.md
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Get-AzureRmRecoveryServicesBackupJob.md
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Get-AzureRmRecoveryServicesBackupProtectionPolicy.md
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Get-AzureRmRecoveryServicesBackupRetentionPolicyObject.md
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Get-AzureRmRecoveryServicesBackupSchedulePolicyObject.md
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Get-AzureRmRecoveryServicesBackupStatus.md
> [REBASE] Added Azure FIle Share support to New and Modify Policy

- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Helpers/HelperUtils.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/CmdletParamEnums.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/CommonModels/Enums.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Properties/Resources.resx
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/IPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureSqlPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/DpmPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/MabPsBackupProvider.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/PsBackupProviderManager.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/RestoreDiskAPIs.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.ServiceClientAdapter/Commands.RecoveryServices.Backup.ServiceClientAdapter.csproj
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.ServiceClientAdapter/RMAPIs/ResourceAPIs.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.ServiceClientAdapter/ServiceClientAdapter.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/ChangeLog.md
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/ParamHelpMsgs.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/RecoveryServicesBackupCmdletBase.cs
- src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Restore-AzureRmRecoveryServicesBackupItem.md
> Added AFS support to restore item

- src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
- src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/RetentionPolicyConversions.cs
- src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/SchedulePolicyConversions.cs
- src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/SubPolicyConversions.cs
- src/RecoveryServices/RecoveryServices.Backup.Helpers/Validations/PolicyValidations.cs
- src/RecoveryServices/RecoveryServices.Backup.Models/AzureDbModels/AzureDbPolicy.cs
- src/RecoveryServices/RecoveryServices.Backup.Models/AzureSqlModels/AzureSqlPolicy.cs
- src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmWorkloadModels/AzureVmWorkloadPolicy.cs
- src/RecoveryServices/RecoveryServices.Backup.Models/BaseObjects.cs
- src/RecoveryServices/RecoveryServices.Backup.Models/Commands.RecoveryServices.Backup.Models.csproj
- src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyRetentionObjects.cs
- src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyScheduleObjects.cs
- src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
- src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureSqlPsBackupProvider.cs
- src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
- src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
- src/RecoveryServices/RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
- src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/PolicyTests.cs
- src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/PolicyTests.ps1
- src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupProtectionPolicy.cs
> Policy cmdlets for mercury for test
